### ISSUE TITLE
mvp ui milestone for gov4git and the plurality book project

### ISSUE THREAD

**Issue by petar** [gov4git/roadmap#1]
This is an umbrella issue covering the MVP UI work for gov4git needed for the Plurality Book Project.

Tasks:
- [ ] TypeScript client library for gov4git operations pertaining to contributors:
  - [ ] Initialize a new user identity
  - [ ] List open ballots
  - [ ] Show ballot specification and current tally
  - [ ] Cast a vote on a ballot

**Comment by gedw99** [comment]
I am building a GUI for Web, Desktop and Mobile.

Using golang and gio. Web runs as WASM.

You can debug the WASM in chorme using https://chrome.google.com/webstore/detail/cc%20%20-devtools-support-dwa/pdcpmagijalfljmkmjngeonclgbbannb if you compile with tinygo. Is has source maps so you actually see the golang code inside the browser. It helps :)

Extensions can also build using the golang and tinygo. I have not done it before, but sure its possible because we can call js from the golang wasm. Need to investigate.

Let me know if your interested in this.

If you want React, FLutter and other guis based on golang, this works well: https://github.com/jerson/openpgp-mobile

**Comment by petar** [comment]
@gedw99 Yes, this is very interesting:

For the gov4git application (this repo), our collaborators from GitHub and Microsoft are already working on developing a prototype web UI, written in JS/TS.

On the other hand, I have also made a decentralized Twitter-over-git (here https://github.com/social4git/social4git) using the same framework as gov4git. This project really needs a mobile UI, in order to effectively demonstrate itself as an alternative to Mastodon/BlueSky/Damus/Twitter. I did some investigation and discovered gio and tailscale's iOS app (which is closed source), but was not able to write a hello world app for iOS myself (mostly because I have too much on my plate).

If there is know-how on your end, this would be a valuable direction to investigate.

**Comment by gedw99** [comment]
Yeah the links to my suggestions is interested but complex. def not everyones cup of tea.

Great to hear that MS and GH are helping out...

socia4git looks awesome :)  Building a GUI for that in GIo looks very doable. Because of go-git it will work everywhere.
I think i can even get it working was WASM in a web browser thanks to the golang FS abstraction that uses indexedDB.
Very doable because your code base is nice and clean btw  - god stuff.

Yep tailscale uses gio for Android app and its open. Have not seen their IOS app in the open.

Def have know how of GIo on my end. We can discuss at the meeting....
